# Generated by Django 5.2.6 on 2025-09-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=10)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
